---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec
  inspec_tests:
    - compliance://cis/cis-centos7-level1

platforms:
  - name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[ssh::default]
    attributes:
